classifiedAds/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('products.urls', namespace='products')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^admin/', admin.site.urls),
]

products/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views

from . import views

app_name = 'products'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^filter/(?P<productFilter>\w+)/$', views.filterProducts, name='filterProducts'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.DetailProduct.as_view(), name='detailProduct'),
    url(r'^buy/(?P<product_id>[0-9]+)/$', views.buyProduct, name='buyProduct'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.Login.as_view(), name='logIn'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^loggedin/$', views.LoggedIn.as_view(), name='loggedIn'),
    url(r'^loggedin/filter/(?P<productFilter>\w+)/$', views.filterSellerItems, name='filterSellerItems'),
    url(r'^loggedin/filter/(?P<product_id>[0-9]+)/$', views.detailSellerProduct, name='detailSellerProduct'),
    url(r'^loggedin/addproduct/$', views.AddProduct.as_view(), name='addProduct'),
    url(r'^loggedin/remove_product/(?P<product_id>[0-9]+)$', views.removeProduct, name='removeProduct'),
    url(r'^loggedin/edit_product/(?P<product_id>[0-9]+)$', views.EditProduct.as_view(), name='editProduct'),
    ]

products/models.py
from django.db import models
from django.contrib.auth.models import User

class Seller(models.Model):
	user = models.OneToOneField(
		User,
		on_delete=models.CASCADE,
		primary_key=True
		)
	address = models.CharField(max_length=100)

	def __str__(self):
		return self.user.username

class Product(models.Model):
	seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
	title = models.CharField(max_length=150)
	category = models.CharField(max_length=100)
	geolocation = Seller(pk=seller).address
	price = models.IntegerField(default=0)
	sold = models.BooleanField(default=False)
	# The following field will be useful in an application with real buyers
	#purchased_by = models.ForeignKey(User)
	description = models.TextField(max_length=1000)
	created = models.DateTimeField('date created', auto_now_add=True)

	def __str__(self):
		return self.title

products/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User

from .models import Seller, Product

class UserForm(ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'username', 'email', 'password',)
		widgets = {
			'first_name': forms.fields.TextInput(attrs={'placeholder': 'e.g. John'})
		}

class SellerForm(ModelForm):
	class Meta:
		model = Seller
		fields = ('address',)


class LoginForm(forms.Form):
	username = forms.CharField(max_length=100)
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)


class ProductForm(ModelForm):
	class Meta:
		model = Product
		fields = ['title', 'category', 'price', 'description']

class FilterForm(forms.Form):
	category = forms.CharField(max_length=100, required=False)
	min_price = forms.IntegerField(required=False)
	max_price = forms.IntegerField(required=False)
	geolocation = forms.CharField(max_length=200, required=False)
	items_per_page = forms.ChoiceField(widget=forms.Select(attrs={"onChange": 'filterForm.submit();'}),
										choices=(
											('3', 3), 
											('5', 5), 
											('10', 10), 
											('20', 20)
											),
										initial=5, required=False
										)

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.utils.decorators import method_decorator 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.edit import FormMixin

from .models import Seller, Product
from .forms import UserForm, SellerForm, LoginForm, ProductForm, FilterForm


class IndexView(FormMixin, generic.ListView):
	template_name = 'products/index.html'
	filter_form = FilterForm
	form_class = FilterForm
	context_object_name = 'products_list'

	def get_queryset(self):
		request_elements = [value for key, value in self.request.GET.items() 
							if len(value)>0 
								and key != 'items_per_page'
								and key != 'page']
		query_set = Product.objects
		if len(request_elements)>0:
			filter_form = self.filter_form(self.request.GET)
			if filter_form.is_valid():
				cd = filter_form.cleaned_data
				if cd['category']:
					category = cd['category']
					query_set = query_set.filter(category=category)
				else: pass
				if cd['min_price']:
					min_price = cd['min_price']
					query_set = query_set.filter(price__gt=min_price)
				else: pass
				if cd['max_price']:
					max_price = cd['max_price']
					query_set = query_set.filter(price__lt=max_price)
				else: pass
				if cd['geolocation']:
					geolocation = cd['geolocation']
					query_set = query_set.filter(seller__address=geolocation)
				else: pass
				return query_set
		else:
			query_set = query_set.all()
			filter_form = self.filter_form()
			self.queryset = query_set
			return query_set

	def get_paginate_by(self, queryset):
		try:
			self.paginate_by = int(self.request.GET['items_per_page'])
		except KeyError:
			self.paginate_by = 5
		return self.paginate_by

	def get_boundform(self):
		filter_form = self.filter_form(self.request.GET)
		self.form = filter_form
		return self.form

	def get(self, request):
		self.form = self.get_boundform()
		self.object_list = self.get_queryset()
		context = self.get_context_data(object_list=self.object_list)
		context['filter_form'] = self.form
		#print(context)
		return render(request, self.template_name, context)


def filterProducts(request, productFilter):
	response = "You're at products which belong to the %s category."
	return HttpResponse(response % productFilter)

class DetailProduct(generic.DetailView):

	def get(self, request, product_id):
		product = Product.objects.get(pk=product_id)
		return render(request, 'products/detail_product.html', {'product': product, 'user': request.user})

def buyProduct(request, product_id):
	return HttpResponse("You've purchased product %s" % product_id)

def register(request):
	#context = RequestContext(request)
	registered = False

	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		seller_form = SellerForm(data=request.POST)
		if user_form.is_valid() and seller_form.is_valid():
			user = user_form.save()
			user.set_password(user.password) #hashes the password with the set_password method
			user.save()
			seller = seller_form.save()
			seller.user = user
			registered = True
			#seller = authenticate(username=user.username, password=user.password)
			#print(seller, ' for %s and %s' % (user.username, user.password))
			#login(request, seller)
			if user.first_name:
				firstName = user.first_name
			else:
				firstName = user.username
			return redirect('products:loggedIn', user=user)
	else:
		user_form = UserForm()
		seller_form = SellerForm()
	return render(request, 'products/registration.html', 
		           {'user_form': user_form, 'seller_form': seller_form, 'registered': registered}
		           )

class Login(generic.View):
	seller_form = LoginForm
	template_name = 'products/login.html'

	def get(self, request, *args, **kwargs):
		seller_form = self.seller_form()
		return render(request, self.template_name, {'seller_form': seller_form})

	def post(self, request, *args, **kwargs):
		seller_form = self.seller_form(data=request.POST)
		if seller_form.is_valid():
			cd = seller_form.cleaned_data
			username = cd['username']
			pwd = cd['password']
			seller = authenticate(username=username, password=pwd)
			print('seller is ', seller)
			if seller is not None:
				if seller.is_active:
					print('Account is active')
					login(request, seller)
					print(seller.username)
					return redirect('/products/loggedin/')
				else:
					print('Accunt is inactive')
					# Write later something more touchy here
					return HttpResponse("Your seller account has been disabled")
			else:
				print('Something went wrong with the input data, seller is None')
				print(request.POST['username'], requsest.POST['set_password'])
				return render(request, 'products/login.html', 
								{'seller_form': seller_form, 'error_message': "username or password wrong"}
								)
		else:
			print('Something went really wrong with the input data, data is invalid')
			return render(request, 'products/login.html', 
							{'error_message': "Please introduce valid data"} 
							)

def logout_view(request):
	logout(request)
	return redirect('/products/')


class LoggedIn(LoginRequiredMixin, generic.View):
	login_url = "/products/login/"
	permission_denied_message = 'Please provide a valid username and password'

	def get(self, request):
		seller = Seller.objects.get(user=request.user)
		products_list = seller.product_set.all().order_by('-created')
		return render(request, 'products/loggedin.html', {'user': request.user, 
															'products_list': products_list}
															)

	@method_decorator(login_required(login_url=login_url))
	def dispatch(self, *args, **kwargs):
		return super(LoggedIn, self).dispatch(*args, **kwargs)


@login_required(login_url='/products/login/')
def loggedIn(request):
	seller = Seller.objects.get(username=user.username)
	product_list = seller.product_set.all().order_by('-created')
	return render(request, 'products/loggedin.html', {'user': request.user, 'products_list': products_list})

@login_required
def filterSellerItems(request, option):
	if option == 'sold':
	    return
	elif option == 'unsold':
	    return
	else:
	    return HttpResponse("In here you'll soon see the items that you've added to the site!")   

def detailSellerProduct(request, product_id):
	return HttpResponse("You're looking at product %s" % product_id)

def removeProduct(request, product_id):
	target_product = Product.objects.get(pk=product_id)
	target_product.delete()
	return redirect('/products/loggedin/')

class AddProduct(LoginRequiredMixin, generic.View):
	login_url = "/products/login/"
	product_form = ProductForm
	template_name = 'products/add_product.html'

	def get(self, request, *args, **kwargs):
		product_form = self.product_form()
		return render(request, self.template_name, {'product_form': product_form})

	def post(self, request, *args, **kwargs):
		product_form = self.product_form(data=request.POST)
		if product_form.is_valid():
			product = product_form.save(commit=False)
			product.created = timezone.now()
			seller = Seller.objects.get(user=request.user)
			product.seller = seller
			product.geolocation = product.seller.address
			product.save()
			return redirect('/products/loggedin/')
		else: return render(request, 
							template_name, 
							{'product_form': product_form, 
								'error_message': 'Please introduce valid data'}
							)

class EditProduct(LoginRequiredMixin, generic.View):
	login_url = "/products/login/"
	product_form = ProductForm

	def get(self, request, product_id):
		product = Product.objects.get(pk=product_id)
		product_form = self.product_form(initial={
												'title': product.title,
												'category': product.category,
												'price': product.price,
												'description': product.description
												})
		return render(request, 'products/edit_product.html', {'product_form': product_form})

	def post(self, request, product_id):
		product = Product.objects.get(pk=product_id)
		product_form = self.product_form(data=request.POST)
		if product_form.is_valid():
			cd = product_form.cleaned_data
			product.title = cd['title']
			product.category = cd['category']
			product.price = cd['price']
			product.description = cd['description']
		product.save()
		return redirect('/products/product/' + product_id)

products/templates/products/_base.html
<!DOCTYPE html>
<html>
<head>
	<title>Sell Everything!</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

products/templates/products/add_product.html
<h1>Sell a brand new product!</h1>

{% if form.errors %}
<p>Please introduce valid data.</p>
{{ form.errors }}
{% endif %}

{% if error_message %}
	<p>{{ error_message }}</p>
{% endif %}

<form id="product_form" method="post" action="{% url 'products:addProduct' %}">
	{% csrf_token %}
	<table>
		<tr>
			<td>{{ product_form.title.label_tag }}</td>
			<td>{{ product_form.title }}</td>
		</tr>
		<tr>
			<td>{{ product_form.category.label_tag }}</td>
			<td>{{ product_form.category }}</td>
		</tr>
		<tr>
			<td>{{ product_form.price.label_tag }}</td>
			<td>{{ product_form.price }}</td>
		</tr>
		<tr>
			<td>{{ product_form.description.label_tag }}</td>
			<td>{{ product_form.description }}</td>
		</tr>
	</table>
	

	<input type="submit" value="submit" />
</form>

products/templates/products/detail_product.html
<h1>{{ product.title }}</h1>

	<table>
		<tr>
			<td>Category</td>
			<td>{{ product.category }}</td>
		</tr>
		<tr>
			<td>Price</td>
			<td>{{ product.price }}</td>
		</tr>
		<tr>
			<td>Published</td>
			<td>{{ product.created }}</td>
		</tr>
		<tr>
			<td>Available in</td>
			<td>{{ product.seller.address }}</td>
		</tr>
				<tr>
			<td>Created by</td>
			<td>{{ product.seller }}</td>
		</tr>
    </table>

{% if product.seller.user.username == user.username %}
	<p><a href="{% url 'products:removeProduct' product.id %}">Delete</a> - 
	<a href="{% url 'products:editProduct' product.id %}">Edit</a></p>
{% endif %}

<p>Description</p>
<span>{{ product.description }}</span>

products/templates/products/edit_product.html
<h1>Edit your product to sell better!</h1>

{% if form.errors %}
<p>Please introduce valid data.</p>
{{ form.errors }}
{% endif %}

{% if error_message %}
	<p>{{ error_message }}</p>
{% endif %}

<form id="edit_product_form" method="post" action="">
	{% csrf_token %}
	<table>
		<tr>
			<td>{{ product_form.title.label_tag }}</td>
			<td>{{ product_form.title }}</td>
		</tr>
		<tr>
			<td>{{ product_form.category.label_tag }}</td>
			<td>{{ product_form.category }}</td>
		</tr>
		<tr>
			<td>{{ product_form.price.label_tag }}</td>
			<td>{{ product_form.price }}</td>
		</tr>
		<tr>
			<td>{{ product_form.description.label_tag }}</td>
			<td>{{ product_form.description }}</td>
		</tr>
	</table>
	

	<input type="submit" value="save" />
</form>

products/templates/products/index.html
{% extends "products/_base.html" %}

{% block content %}

<h1>Sell Everything!</h1>

{% if user.is_active %}
	<p>{{ user.username }}</p>
{% endif %}

<p>Filter by</p>
<form name="filterForm" id="filter_form" method="get" action="{% url 'products:index' %}">
<table>
	<tr>
		<td>{{ filter_form.category.label_tag }}</td>
		<td>{{ filter_form.category }}</td>
	</tr>
	<tr>
		<td>Price:</td>
		<td>from {{ filter_form.min_price }} to {{ filter_form.max_price }}</td>
	</tr>
	<tr>
		<td>{{ filter_form.geolocation.label_tag }}</td>
		<td>{{ filter_form.geolocation }}</td>
	</tr>
</table>
<input type="submit" value="submit" />

<p>{{ filter_form.items_per_page.label_tag }} {{ filter_form.items_per_page }}</p>

</form> 

{% if products_list %}
    <table id="id_products_table">
    	{% for product in products_list %}
    	<tr>
    		<td><a href="{% url 'products:detailProduct' product.id %}">{{ product.title }}</a></td>
    	</tr>
        {% endfor %}
    </table><br />

    <div>
    	<span class="step-links">
    		{% if page_obj.has_previous %}
    			<a href="?page={{ page_obj.previous_page_number }}">previous</a>
    		{% endif %}

    		<span class="current">
    			Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    		</span>

    		{% if page_obj.has_next %}
    			<a href="?page={{ page_obj.next_page_number }}">next</a>
    		{% endif %}
    	</span>
    </div>
{% else %}
    <p>No products yet available. Would you like to <a href="{% url 'products:logIn' %}">sell</a> something??</p>
{% endif %}

<p><a href="{% url 'products:register' %}">Become a Seller!</a></p>
<p><a href="{% url 'products:logIn' %}">Sell!</a></p>

{% endblock %}

products/templates/products/loggedin.html
{% if user.is_active %}
	<h1>Welcome {{ user.username }}!</h1>
{% else %}
    <h1>Hmmm... it doesn't look like you should be here....</h1>
 {% endif %}

 {% if products_list %}
 	<a href="{% url 'products:addProduct' %}">Add a new product!</a>
    <ul>
        {% for product in products_list %}
            <li><a href="{% url 'products:detailProduct' product.id %}">{{ product.title }}</a> - <a href="{% url 'products:removeProduct' product.id %}">delete</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>You haven't yet uplpaded any product for sell! <a href="{% url 'products:addProduct' %}">Upload</a> one now!</p>
{% endif %}

 <p><a href="{% url 'products:logout' %}">Log out</a></p>

products/templates/products/login.html
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{{ form.errors }}
{% endif %}

{% if error_messages %}
	<p>{{ error_messages }}</p>
{% endif %}

{% if next %}
	{% if user.is_authenticated %}
		<p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
	{% else %}
		<p>Please login to see this page.</p>
	{% endif %}
{% endif %}

<h1>Log in</h1>

<form id="login_form" method="post" action="{% url 'products:logIn' %}">
	{% csrf_token %}
	<!--
	Email: <input type="text" name="username" value="seller@seller.com" size="50" />
	Password: <input type="password" name="password" value="" size="50" />
	<br />
	-->

	<!--
	{{ seller_form.as_p }}
	-->
	<table>
		<tr>
			<td>{{ seller_form.username.label_tag }}</td>
			<td>{{ seller_form.username }}</td>
		</tr>
		<tr>
			<td>{{ seller_form.password.label_tag }}</td>
			<td>{{ seller_form.password }}</td>
		</tr>
	</table>
	

	<input type="submit" value="submit" />
</form>

products/templates/products/registration.html
<h1>Join the single best selling platform!</h1>

<form id="user_form" method="post" action="{% url 'products:register' %}" encrypte="multipart/form-data">
    {% csrf_token %}
	{{ user_form.non_field_errors }}
	{{ seller_form.non_field_errors }}
	<div class="fieldWrapper">
		{{ user_form.first_name.errors }}
		<label for="{{ user_form.first_name.id_for_label }}">First name:</label>
		{{ user_form.first_name }}
	</div>
	<br />
	<div class="fieldWrapper">
		{{ user_form.last_name.errors }}
		<label for="{{ user_form.last_name.id_for_label }}">Last name:</label>
		{{ user_form.last_name }}
	</div>
	<br />
	<div class="fieldWrapper">
		{{ user_form.username.errors }}
		<label for="{{ user_form.username.id_for_label }}">Username:</label>
		{{ user_form.username }}
	</div>
	<br />
	<div class="fieldWrapper">
		{{ user_form.email.errors }}
		<label for="{{ user_form.email.id_for_label }}">E-mail:</label>
		{{ user_form.email }}
	</div>
	<br />
	<div>
		<label for="confirm_email">Confirm e-mail:</label>
		<input id="confirm_email" maxlength="254" name="confirm_email" type="email">
	</div>
	<br />
	<div class="fieldWrapper">
		{{ seller_form.address.errors }}
		<label for="{{ seller_form.address.id_for_label }}">Address:</label>
		{{ seller_form.address }}
	</div>
	<br />
	<div class="fieldWrapper">
		{{ user_form.password.errors }}
		<label for="{{ user_form.password.id_for_label }}">Password:</label>
		{{ user_form.password }}
	</div>	
	<br />
	<div class="fieldWrapper">
	    {{ confirm_password.errors }}
		<label for="confirm_password">Confirm password:</label>
		<input id="confirm_password" name="confirm_password" type="password">
	</div>
	<br />
	<input type="submit" name="submit" value="Register" />
</form>